### ISSUE TITLE
能不能提供个编译好的版本

### ISSUE THREAD

**Issue by zhenhappy** [ChiChou/GlobalWebInspect#1]
老大, 这个插件真的是非常好的东西, 能不能提供个编译好的版本, 本人是前端开发, 对于我来说这个就是开发神器, 但是由于不太熟悉越狱开发这块, 而且越狱开发这块教程也非常少, 基本不太可能自己编译出来, 而且这个可能不用版本编译方法也不一样, 所以烦请老大提供个可以直接安装的二进制包

**Comment by ChiChou** [comment]
https://github.com/ChiChou/GlobalWebInspect/releases/tag/beta

scp 到设备上然后 `dpkg -i .deb`

**Comment by zhenhappy** [comment]
@ChiChou 谢谢老大了

**Comment by ChiChou** [comment]
首次安装需要重新插拔 USB，并 home 上划关闭目标应用
