### ISSUE TITLE
mac远程调试真机小程序闪退

### ISSUE THREAD

**Issue by tsl-mousetail** [ChiChou/GlobalWebInspect#10]
机型 iphone6s
ios版本 14.5.1
mac版本 macOS Big Sur Version11.7.10， 
safari版本 16.6.1

手机打开小程序，当在safrari上找到手机，点击对应网页的时候，手机端直接闪退，导致无法调试，重启多次依然如此
崩溃日志：

`{"app_name":"WeChat","timestamp":"2024-02-29 12:15:29.00 +0800","app_version":"8.0.29","slice_uuid":"74187244-b4b5-3f6f-ae72-b74abd8c8074","adam_id":414478124,"build_version":"8.0.29.35","platform":2,"bundleID":"com.tencent.xin","share_with_app_devs":0,"is_first_party":0,"etl_key":"3","bug_type":"109","os_version":"iPhone OS 14.5.1 (18E212)","incident_id":"04182E11-B98E-4B2F-BB6E-409D48AD2760","name":"WeChat"}
Incident Identifier: 04182E11-B98E-4B2F-BB6E-409D48AD2760
CrashReporter Key:   7ddfd6d8a3a8a3b8af4cbcdc142b9f367edb44c8
Hardware Model:      iPhone8,1
Process:             WeChat [75814]
Path:                /private/var/containers/Bundle/Application/5AF7E550-D70C-43FB-BABC-74C8733EA8A1/WeChat.app/WeChat
Identifier:          com.tencent.xin
Version:             8.0.29.35 (8.0.29)
AppStoreTools:       14A305
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.tencent.xin [421]

Date/Time:           2024-02-29 12:15:26.8121 +0800
Launch Time:         2024-02-29 12:14:58.0984 +0800
OS Version:          iPhone OS 14.5.1 (18E212)
Release Type:        User
Baseband Version:    8.52.01
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Subtype: KERN_PROTECTION_FAILURE at 0x000000016cfee3a0
VM Region Info: 0x16cfee3a0 is in 0x16cf6c000-0x16cff4000;  bytes after start: 533408  bytes before end: 23647
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      Stack Guard              16cf68000-16cf6c000 [   16K] ---/rwx SM=NUL  
--->  Stack                    16cf6c000-16cff4000 [  544K] rw-/rwx SM=PRV  thread 25
      Stack Guard              16cff4000-16cff8000 [   16K] ---/rwx SM=NUL  

Termination Signal: Bus error: 10
Termination Reason: Namespace SIGNAL, Code 0xa
Terminating Process: exc handler [75814]
Triggered by Thread:  2

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0:
0   libsystem_kernel.dylib        	0x00000001c64b0908 0x1c64ad000 + 14600
1   libsystem_kernel.dylib        	0x00000001c64afd0c 0x1c64ad000 + 11532
2   CoreFoundation                	0x000000019a7bdc90 0x19a724000 + 629904
3   CoreFoundation                	0x000000019a7b8090 0x19a724000 + 606352
4   CoreFoundation                	0x000000019a7b76a8 0x19a724000 + 603816
5   GraphicsServices              	0x00000001b0e67570 0x1b0e64000 + 13680
6   UIKitCore                     	0x000000019d0d5370 0x19c5a6000 + 11727728
7   UIKitCore                     	0x000000019d0da8ec 0x19c5a6000 + 11749612
8   WeChat                        	0x000000010a040968 0x104204000 + 98814312
9   libdyld.dylib                 	0x000000019a496140 0x19a495000 + 4416

Thread 1 name:  JavaScriptCore bmalloc scavenger
Thread 1:
0   libsystem_kernel.dylib        	0x00000001c64d4580 0x1c64ad000 + 161152
1   libsystem_pthread.dylib       	0x00000001e2c1130c 0x1e2c0e000 + 13068
2   libc++.1.dylib                	0x00000001ae5cca20 0x1ae5c0000 + 51744
3   JavaScriptCore                	0x00000001a435f5b0 0x1a3484000 + 15578544
4   JavaScriptCore                	0x00000001a4363ddc 0x1a3484000 + 15597020
5   JavaScriptCore                	0x00000001a43637f8 0x1a3484000 + 15595512
6   JavaScriptCore                	0x00000001a4364f10 0x1a3484000 + 15601424
7   libsystem_pthread.dylib       	0x00000001e2c17c78 0x1e2c0e000 + 40056
8   libsystem_pthread.dylib       	0x00000001e2c1c878 0x1e2c0e000 + 59512

Thread 2 name:  WebThread
Thread 2 Crashed:
0   ???                           	0x000000016cfee3a0 0 + 6123611040
1   CoreFoundation                	0x000000019a7be780 0x19a724000 + 632704
2   CoreFoundation                	0x000000019a7be680 0x19a724000 + 632448
3   CoreFoundation                	0x000000019a7bd9d4 0x19a724000 + 629204
4   CoreFoundation                	0x000000019a7b7ef0 0x19a724000 + 605936
5   CoreFoundation                	0x000000019a7b76a8 0x19a724000 + 603816
6   WebCore                       	0x00000001a74c4a9c 0x1a6985000 + 11795100
7   libsystem_pthread.dylib       	0x00000001e2c17c78 0x1e2c0e000 + 40056
8   libsystem_pthread.dylib       	0x00000001e2c1c878 0x1e2c0e000 + 59512

Thread 3:
0   libsystem_kernel.dylib        	0x00000001c64d4580 0x1c64ad000 + 161152
1   libsystem_pthread.dylib       	0x00000001e2c1130c 0x1e2c0e000 + 13068
2   ilink_network                 	0x000000011809ea24 0x117fc8000 + 879140
3   ilink_network                 	0x0000000118074510 0x117fc8000 + 705808
4   ilink_network                 	0x0000000118035850 0x117fc8000 + 448592
5   libsystem_pthread.dylib       	0x00000001e2c17c78 0x1e2c0e000 + 40056
6   libsystem_pthread.dylib       	0x00000001e2c1c878 0x1e2c0e000 + 59512
`

**Comment by tsl-mousetail** [comment]
![image](https://github.com/ChiChou/GlobalWebInspect/assets/65294282/1ee08a0e-41e5-448d-b88f-91481528cb9b)
点击ren任何一个App都会闪退

**Comment by ChiChou** [comment]
这个插件用过滤器限制了只会注入 webinspectord，app 是不会去 hook 的。建议检查一下是不是和其他的包有冲突

**Comment by tsl-mousetail** [comment]
我换了一个手机就可以了
