### ISSUE TITLE
ios11.3.1好像不行？？

### ISSUE THREAD

**Issue by hectorqin** [ChiChou/GlobalWebInspect#2]
麻烦大神看看

**Comment by ChiChou** [comment]
更新代码。首次 `make install` 之后需要重新插拔手机 USB，双击 home 上划关闭 App 重新打开。

**Comment by hectorqin** [comment]
可以了，谢谢大神，但是调试的时候会弹出好多个JSContext。。不知道是什么问题

**Comment by ChiChou** [comment]
没有问题，请自行搜索 JavaScriptCore 在 iOS 开发中的应用

**Comment by zhenhappy** [comment]
楼上这位大哥的1.3.1可以用了是吧, 为何我的9.3.3重新安装了老大最新版本的, 关机重启注销, 重新拔插数据线, 结束所有程序进程, 还是只有Safari可以调试, 微信, 钉钉的内嵌页试了都不行
```
launchctl list | grep webinspectord
872	1	com.apple.webinspectord
```
看了这个进程也是有运行的

**Comment by ChiChou** [comment]
@zhenhappy 真机测试通过

**Comment by zhenhappy** [comment]
> @zhenhappy 真机测试通过

@ChiChou 完美了, 编译了最新的ios9分支后成功了, 多谢大神
