### ISSUE TITLE
ARM64e的PAC导致无法正常使用。

### ISSUE THREAD

**Issue by CodeTips** [ChiChou/GlobalWebInspect#5]
KERN_INVALID_ADDRESS at 0x20000001a68a9490 -> 0x00000001a68a9490 (possible pointer authentication failure)

**Comment by ChiChou** [comment]
我现在没有 A12 的测试设备

**Comment by NyaMisty** [comment]
iOS 14.2 A12测试反馈是一切正常的，测试了Telegram和WeChat的webview。
@CodeTips 检查下你是不是按照arm64e编译了，当用arm64e编译时能够复现跟你一模一样的问题。直接使用arm64就可以了

**Comment by CodeTips** [comment]
@NyaMisty 感谢，去掉arm64e 可以正常使用。
