### ISSUE TITLE
6s 15.7.5无法安装

### ISSUE THREAD

**Issue by zxerqw** [ChiChou/GlobalWebInspect#8]
可以支持一下这个版本吗？
安装提示 package architecture (iphoneos-arm) does not match system (iphoneos-arm64)

**Comment by ChiChou** [comment]
文件是 fat binary，同时包含 32 位和 64 位，不是我这的问题

**Comment by zxerqw** [comment]
ok，那可能是我越狱方式的问题。

**Comment by fan5657** [comment]
哈喽👋，我也遇到了这个问题，请问是越狱是改成rootful？

**Comment by zxerqw** [comment]
> 哈喽👋，我也遇到了这个问题，请问是越狱是改成rootful？

没有，试了试好像都不行就没弄了

**Comment by zxerqw** [comment]
> 哈喽👋，我也遇到了这个问题，请问是越狱是改成rootful？

今天重试了一次，确实是rootless不行，转换了装上去也无效，换成rootful就可以的

**Comment by ChiChou** [comment]
如果是 rootless 的差异，可以尝试自行编译源码

**Comment by zxerqw** [comment]
这个确实不会。。。
