### ISSUE TITLE
ios 14.2 失效

### ISSUE THREAD

**Issue by chen1sheng** [ChiChou/GlobalWebInspect#9]
求问大佬。
第一次安装成功且可以正常调试小程序，后来重启手机重新越狱之后就失效了，尝试卸载重装也没用
能看到插件在运行：
![image](https://github.com/ChiChou/GlobalWebInspect/assets/44370914/620b91e5-5378-4bf2-9231-96bdbdf4edad)
但是小程序这边只能看到基础的frame.html，没有实际的业务代码：
![image](https://github.com/ChiChou/GlobalWebInspect/assets/44370914/7437114e-e029-4376-aabf-cb46b0e79bb5)

**Comment by ChiChou** [comment]
1. `webinspectord` 是系统进程，不是插件的进程
2. 能看到第三方 App 出现在菜单里就说明插件成功安装了，不显示 JSContext 可能是代码执行顺序先后导致的，建议 SpringBoard 里上划关掉 app 重试

**Comment by chen1sheng** [comment]
@ChiChou 感谢大佬回复！！！
但是我还是不行，现在Safari的开发连接就直接一直提示连接中，连不上了😂
<img width="417" alt="image" src="https://github.com/ChiChou/GlobalWebInspect/assets/44370914/fc31690e-c9db-4b2c-aa73-6c9681866a0a">

重启SpringBoard关掉app进入也只能看到基础的frame.html 尝试了重新越狱和安装插件也不行，有可以进一步调试或者查看失败原因的方法吗？

**Comment by chen1sheng** [comment]
彻底重装了系统，重新越狱，重新装插件，神奇的又可以了。感谢大佬回复
